#!/bin/sh
if [ -e /usr/local/lib/libaquaterm.dylib ]; then
    rm /usr/local/lib/libaquaterm.dylib
fi
if [ -e /usr/local/lib/libaquaterm.1.0.0.dylib ]; then
    rm /usr/local/lib/libaquaterm.1.0.0.dylib
fi
if [ -e /usr/local/lib/libaquaterm.1.0.1.dylib ]; then
    rm /usr/local/lib/libaquaterm.1.0.1.dylib
fi
if [ -e /usr/local/lib/libaquaterm.1.1.0.dylib ]; then
    rm /usr/local/lib/libaquaterm.1.1.0.dylib
fi
if [ -e /usr/local/include/aquaterm/aquaterm.h ]; then
    rm /usr/local/include/aquaterm/aquaterm.h
fi
if [ -e /usr/local/include/aquaterm/AQTAdapter.h ]; then
    rm /usr/local/include/aquaterm/AQTAdapter.h
fi

exit 0
