#!/bin/sh
if [ -e /usr/local/lib/libaquaterm.dylib ]; then
    rm /usr/local/lib/libaquaterm.dylib
fi
if [ -e /usr/local/lib/libaquaterm.1.0.0.dylib ]; then
    rm /usr/local/lib/libaquaterm.1.0.0.dylib
fi

exit 0