#!/bin/sh

# Installer postflight script

VERSIONS=".1.0.0 .1.0.1 .1.1.0"
PREFIX=/usr/local

LIBDIR=$PREFIX/lib
HEADERDIR=$PREFIX/include/aquaterm

## Remove symlinks to framework in /usr/local/lib
for version in "" $VERSIONS
do
    link=$LIBDIR/libaquaterm${version}.dylib
    echo "[Checking] $link"

    if [ -e $link ]; then
        rm $link
        echo "[Deleted] $link"
    fi
done

## Remove symlinks to framework in /usr/local/include/aquaterm
if [ -e $HEADERDIR ]; then
    rm -rf $HEADERDIR
    echo "[Removed old] $HEADERDIR"
fi

exit 0
